/**
 * Backward-compatible barrel file for `lib/chat/api`.
 *
 * The monolithic api.ts has been decomposed into focused domain modules:
 *   - event-types.ts   — SSE event type definitions
 *   - event-parser.ts  — parseAssistantEvent + attachment helpers
 *   - conversations.ts — conversation CRUD + groups
 *   - messages.ts      — message history, sending, attachments
 *   - interactions.ts  — secret/confirmation/contact/question submissions
 *   - surfaces.ts      — surface actions, content, artifact download
 *   - stream.ts        — SSE stream transport with reconnect + watchdog
 *   - assistant.ts     — assistant discovery, chat context, identity
 *
 * All public exports are re-exported here so existing `import … from
 * "@/domains/chat/lib/api"` paths continue to work. New code should import from
 * the domain module directly.
 */

// DO NOT ADD ONTO THIS FILE. USE THE AUTOGENERATED TANSTACK QUERY HOOKS INSTEAD.
// THIS IS HERE JUST FOR LEGACY COMPATIBILITY.

// ---- client (shared error type) ----
export { ApiError } from "@/domains/chat/lib/client.js";

// ---- event-types ----
export type {
  AllowlistOption,
  AssistantActivityPhase,
  AssistantActivityReason,
  AssistantActivityStateEvent,
  AssistantEvent,
  AssistantOutboundAttachment,
  AssistantSyncChangedEvent,
  AssistantTextDeltaEvent,
  AvatarUpdatedEvent,
  ChatMessage,
  ChatMessageToolCall,
  CompactionCircuitClosedEvent,
  CompactionCircuitOpenEvent,
  ConfirmationDecision,
  ConfirmationRequestEvent,
  ContactRequestEvent,
  ConversationErrorEvent,
  ConversationListInvalidatedEvent,
  ConversationListInvalidatedReason,
  ConversationTitleUpdatedEvent,
  DirectoryScopeOption,
  DiskPressureStatusChangedEvent,
  GenerationCancelledEvent,
  GenerationHandoffEvent,
  IdentityChangedEvent,
  MessageCompleteEvent,
  MessageDequeuedEvent,
  MessageQueuedDeletedEvent,
  MessageQueuedEvent,
  MessageRequestCompleteEvent,
  NavigateSettingsEvent,
  NotificationIntentEvent,
  OpenUrlEvent,
  PendingToolConfirmation,
  QuestionEntry,
  QuestionOption,
  QuestionRequestEvent,
  QuestionResponseEntry,
  QuestionSubmission,
  ScopeOption,
  SecretRequestEvent,
  StreamErrorEvent,
  SubagentEventWrapperEvent,
  SubagentInnerEvent,
  SubagentSpawnedEvent,
  SubagentStatus,
  SubagentStatusChangedEvent,
  ToolResultEvent,
  ToolUseStartEvent,
  UISurfaceCompleteEvent,
  UISurfaceDismissEvent,
  UISurfaceShowEvent,
  UISurfaceUpdateEvent,
  UnknownEvent,
  UsageUpdateEvent,
} from "@/domains/chat/lib/event-types.js";
export { normalizeQuestionRequest } from "@/domains/chat/lib/event-types.js";

// ---- event-parser ----
export {
  parseAssistantEvent,
  readEventConversationKey,
  toDisplayAttachments,
} from "@/domains/chat/lib/event-parser.js";

// ---- conversations ----
export type {
  Conversation,
  ConversationGroup,
  ReorderConversationUpdate,
} from "@/domains/chat/lib/conversations.js";
export {
  abortSubagent,
  analyzeConversation,
  archiveConversation,
  cancelGeneration,
  canMarkRead,
  canMarkUnread,
  createGroup,
  deleteGroup,
  fetchGroups,
  forkConversation,
  isBackgroundConversation,
  listConversations,
  markConversationSeen,
  markConversationUnread,
  parseConversation,
  renameConversation,
  reorderConversations,
  reorderGroups,
  unarchiveConversation,
  updateGroup,
  fetchSubagentDetail,
} from "@/domains/chat/lib/conversations.js";
export type { SubagentDetailResponse } from "@/domains/chat/lib/conversations.js";

// ---- messages ----
export type {
  ChatHistoryResult,
  PostMessageResult,
  RuntimeAttachment,
  RuntimeMessage,
  RuntimeSubagentNotification,
  RuntimeToolCall,
  UploadAttachmentResult,
} from "@/domains/chat/lib/messages.js";
export {
  deleteQueuedMessage,
  fetchConversationMessages,
  getChatHistory,
  mapRuntimeToolCalls,
  normalizeContentOrder,
  normalizeTextSegments,
  pollForResponse,
  postChatMessage,
  uploadChatAttachment,
} from "@/domains/chat/lib/messages.js";

// ---- interactions ----
export type { SubmitSecretResponseResult } from "@/domains/chat/interactions/api.js";
export {
  getPendingInteractions,
  listConversationKeysWithPendingInteractions,
  submitConfirmation,
  submitContactPrompt,
  submitQuestionResponse,
  submitSecretResponse,
  submitTrustRule,
} from "@/domains/chat/interactions/api.js";

// ---- surfaces ----
export type { SurfaceContentResponse } from "@/domains/chat/lib/surfaces.js";
export {
  downloadArtifact,
  fetchSurfaceContent,
  submitSurfaceAction,
} from "@/domains/chat/lib/surfaces.js";

// ---- stream ----
export type {
  ChatEventStream,
  ChatEventStreamOptions,
  ChatStreamReconnectCause,
} from "@/domains/chat/lib/stream.js";
export { subscribeChatEvents } from "@/domains/chat/lib/stream.js";

// ---- assistant ----
export type {
  AssistantIdentity,
  ChatContext,
} from "@/domains/chat/lib/assistant.js";
export {
  fetchAssistantIdentity,
  getChatContext,
} from "@/domains/chat/lib/assistant.js";
